name: Terraform Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

permissions:
  id-token: write
  pull-requests: write
  contents: write

jobs:
  terraform_tasks:
    name: Terraform Tasks
    runs-on: ubuntu-latest
    outputs:
      plan_output: ${{ steps.plan.outputs.stdout }}
      report_path: ${{ steps.plan_report.outputs.report_path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GithubActionsTerraform

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: ">= 1.11.4"

      # TFlint Integration
      - name: Install TFlint
        run: |
          wget https://github.com/terraform-linters/tflint/releases/download/v0.50.2/tflint_linux_amd64.zip # Replace with the latest TFlint version
          unzip tflint_linux_amd64.zip
          sudo mv tflint /usr/local/bin/
          tflint --version

      - name: Run TFlint
        id: tflint
        run: tflint --init && tflint -f compact
        working-directory: ./

      # Checkov Integration
      - name: Install Checkov
        run: |
          pip3 install --upgrade pip
          pip3 install checkov

      - name: Run Checkov
        id: checkov
        run: checkov -d . --framework terraform --soft-fail
        working-directory: ./

      # Terraform Steps
      - name: Initialize Terraform
        id: init
        run: terraform init -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" -backend-config="key=terraform.tfstate" -backend-config="region=${{ secrets.AWS_REGION }}"
        working-directory: ./

      - name: Validate Terraform
        id: fmt_and_validate
        run: terraform fmt && terraform validate
        working-directory: ./

      - name: Generate Terraform Plan
        id: plan
        run: terraform plan -var-file="terraform.tfvars" -lock=false > plan.txt
        working-directory: ./
        shell: bash

      - name: Create Plan Output Text File
        id: plan_report
        run: |
          mkdir -p reports
          echo "#Deployment Report" > reports/report.txt
          echo "This file was generated during the github actions workflow run." >> reports/report.txt
          echo "" >> reports/report.txt
          echo "## Terraform Plan Output" >> reports/report.txt
          cat plan.txt >> reports/report.txt
          echo "report_path=reports/report.txt" >> "$GITHUB_OUTPUT"
        working-directory: ./
        shell: bash

  report_generation:
    name: Report Generation
    runs-on: ubuntu-latest
    needs: terraform_tasks
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Report Path
        id: get_report_path
        run: echo "${{ needs.terraform_tasks.outputs.report_path }}"

      - name: Commit and push the report
        run: |
          git config --global user.name "Raghavarao1201"
          git config --global user.email "raghavaraomachiraju@gmail.com"
          git add reports/report.txt
          git commit -m "Add deployment report"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./

  comment_plan_pr:
    name: Comment Plan on Pull Request
    runs-on: ubuntu-latest
    needs: terraform_tasks
    if: github.event_name == 'pull_request'
    steps:
      - name: Get Terraform Plan
        id: get_plan
        run: echo "${{ needs.terraform_tasks.outputs.plan_output }}" > plan.txt

      - name: Comment Plan to Pull Request
        uses: actions/github-script@v7
        env:
          PLAN: "${{ needs.terraform_tasks.outputs.plan_output }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const planOutput = fs.readFileSync('./plan.txt', 'utf8');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.event.pull_request.number,
              body: planOutput
            });

  terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: [terraform_tasks, report_generation, comment_plan_pr]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GithubActionsTerraform

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: ">= 1.11.4"

      - name: Initialize Terraform
        id: init
        run: terraform init -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" -backend-config="key=terraform.tfstate" -backend-config="region=${{ secrets.AWS_REGION }}"
        working-directory: ./

      - name: Apply Terraform
        id: apply
        run: terraform apply -auto-approve -lock=false -var-file="terraform.tfvars"
        working-directory: ./

      #- name: Terraform Destroy
      #  id: destroy
      #  run: terraform destroy -auto-approve -lock=false -var-file="terraform.tfvars"
